### ISSUE TITLE
Adicionar novos colaboradores a Organização

### ISSUE THREAD

**Issue by vmesel** [grupy-sp/encontros#44]
Pessoal,

Eu e o Regis estamos há algum tempo na comunidade organizando e gerenciando os eventos, mas ainda não recebemos acesso à organização. Como poderíamos providenciar este acesso?

**Comment by rg3915** [comment]
Eu já tenho acesso, mas tem que pedir para os mais velhos de casa. Eric é
um deles.

Em 09/11/2016 6:33 PM, "Vinicius Mesel" notifications@github.com escreveu:

**Comment by vmesel** [comment]
@erichideki você pode me dar acesso a este repositório?

**Comment by drgarcia1986** [comment]
eu tenho privilégios na organização, mas nunca usei, só interagi com esse repositório até hoje.
reparei que vc @vmesel já é contribuidor dele, oq vc precisa na organização ? posso lhe ajudar com algo

**Comment by vmesel** [comment]
@drgarcia1986 a questão não é ser contribuidor ou não, as vezes fica mais fácil postar um PR quando você está em um grupy, ai todos teriam acesso simultâneo no evento, ao invés de termos de esperar os PRs serem analisados(obviamente que as análises estão rápidas). E também é importante para o grupo poder ser como fala que é: DA COMUNIDADE, onde as pessoas possam editar

**Comment by drgarcia1986** [comment]
@vmesel mas vc como contribuidor do repositório não pode fazer review e merge dos PRs ? 🤔  se sim (que acho que sim) já são umas 4 pessoas fazendo isso (eu, vc, @rg3915 e @erichideki ) sendo vc e o @rg3915 os mais ativos atualmente. Para oq vc precisa acho que vc já tem os privilégios suficientes, se eu estiver enganado me fale por favor

**Comment by vmesel** [comment]
@drgarcia1986 sim cara, mas por exemplo: e se o régis quiser tocar a proposta do novo site para a comunidade, ele teria que hospedar o projeto na própria conta e o projeto é para o GRUPY. A questão que eu quero levantar é a seguinte: para que então temos a organização se ninguém faz uso dos recursos dela?

**Comment by drgarcia1986** [comment]
e você acha que para fazer uso precisamos aumentar o numero de colabores com privilégios de administradores ? 🤔  
BTW, se estiverem pensando em fazer um site novo, podem fazer um PR [aqui](https://github.com/grupy-sp/grupy-sp.github.io)

IMO, aumentar o numero de colaboradores da organização sem um proposito real não faz sentido. 

Você expressou com razão a preocupação em relação a esse repositório que estamos, mas aqui você já é um colaborador, já pode nos ajudar a revisar os PR e puxar a orelha de quem estiver commitando direto no master. Para outros repositórios, basta você explicar sua ideia e a galera mensura se vale um repositório na organização ou não.

Veja, essas são apenas minhas opiniões e atualmente estou bem afastado, seria legal mais pessoas opinarem.

**Comment by eduardompinto** [comment]
IMO, isso não é uma issue! Não entendi o que te impede de mandar prs aqui e nos outros repos.

**Comment by vmesel** [comment]
@pecota isto é uma questão que eu já venho debatendo há muitos eventos! Precisamos nos organizar melhor para permitirmos que o GruPy tenha uma expansão, se a organização que utilizamos apenas 1/3 está realmente ativa na comunidade(ainda que seja pela web) ela deve ser remanejada para que coloque mais pessoas que estejam aptas a organizar o evento e coisas sobre o GruPy-SP

**Comment by drgarcia1986** [comment]
@vmesel para fazer os encontros usamos o meetup, vc já é administrador la? se não e vc que está puxando os encontros, vc deveria ser "promovido" a administrador la (posso providenciar isso pra vc eu acho).

Aqui fica o histórico dos nossos eventos, achei legal vc falar que já seria bacana ir alimentando o `md` do encontro enquanto ele for rolando, então você como contribuidor do repo já pode ir fazendo isso. 

Sobre a organização do github, não vejo motivos ainda para adicionar mais colaboradores, se alguém que já for colaborador discordar pode tomar a liberdade e eleger quem achar que faz sentido.

**Comment by drgarcia1986** [comment]
acabei de confirmar, vc está como organizador no meetup (junto com mo galera inclusive, gente pra caramba) sendo assim, em relação a ferramenta utilizada para organizar os encontros já temos um numero bem legal de colaboradores 👍

**Comment by vmesel** [comment]
sim eu sou admin no meetup, mas mesmo assim eu discordo de termos poucas pessoas responsáveis na administração da organização já que eu acho essencial que todos possam participar de decisões, se não, não seria uma comunidade, seria uma empresa... Mas gostaria de ouvir mais opiniões sobre o assunto pois é interessante saber de todos os envolvidos!

**Comment by drgarcia1986** [comment]
Ser membro da org no github não da (nem tira) nenhum privilégio de participar das decisões da comunidade, só permite vc criar ou não repositórios vinculados a organização.

bom, dei minha opinião, se mais alguém quiser discutir a respeito fique a vontade, e como falei, se alguém que tiver os privilégios necessários quiser incluir mais pessoas, fique a vontade.

**Comment by erichideki** [comment]
Vinícius, respondendo seus questionamentos, na minha visão:

> Para que então temos a organização se ninguém faz uso dos recursos dela?

O GruPy-SP hoje tem: Google Groups, Twitter, Facebook, Slack, Meetup e Github. Esses são itens de posse da comunidade. 

Considero os mais importantes, do maior ao menor: Meetup, Google Groups, Github. Facebook, Twitter e Slack são ativos complementares, não essenciais.

O Meetup tem como coordenador original eu, isso porque eu criei a página e tá atrelado a minha conta. Outras pessoas que se interessaram e quiseram colaborar, colocamos como organizador, tendo poderes para criar eventos e gerenciar diversas coisas por lá. 

Atualmente temos 12 pessoas com poderes para isso. Acho esse número até demais pra ser sincero. Tem gente lá que nunca vi ou ouvi falar e tem acesso a isso, não desmerecendo o trabalho e a colaboração, mas pelo que vi, a pessoa organizou um encontro e já tem direito para fazer o que bem entender na página.

O que acho justo é: Se a pessoa quer organizar um evento, coloca ela como organizador do evento, não organizador do meetup. Se a pessoa organizou mais de 3 eventos, é viável adicionar como coordenador, se quiser continuar com o trabalho.

Google Groups: Sou um dos moderadores. Acredito que hajam mais dois, um o Bruno Gola, se não me engano, e Luciano Ramalho. Ainda considero a ferramenta excelente para trocas de ideias, comunicados, e principalmente, discussões como essas deveriam estar lá, registrado para que todos possam opinar. Aqui temos 4 pessoas dando pitaco. Lá são 300.

Github: Ativos no Github acredito que seja eu, Diego e Régis. Todos diariamente acessam o github e rapidamente aceitam PR's feitos. Em algum momento, Vinícius, você se sentiu prejudicado, limitado por não ser organizador no Github? Se sim, resolvemos isso em 1 minuto.

Para mim, ferramenta 'oficial' da comunidade não tem valor. De todos acima, é apenas mais um meio de comunicação. Se a pessoa quer organizar um evento do GruPy, não precisa fazer no meetup. Marca um evento no Facebook e manda bala. Saca?

As ferramentas foram criadas apenas para facilitar o gerenciamento, e pra mim tem pouco valor. Mas qualquer pessoa, inclusive você, se quiser acesso, sem problemas.

O que questiono é o intuito, não o acesso.

Respondendo sua pergunta, tem pessoas que usam as ferramentas. O Régis por exemplo tá tocando o barco. Então não concordo com a afirmação de que não tem ninguém com acesso. Tem pessoas que são comprometidas com a comunidade que estão dispostas a ajudar e fornecer o que for necessário para fazer acontecer, não necessariamente tenho que dar acesso as ferramentas.

> Discordo de termos poucas pessoas responsáveis na administração da organização já que eu acho essencial que todos possam participar de decisões, se não, não seria uma comunidade, seria uma empresa

Todos podem fazer o que bem entender no GruPy, opinar, organizar eventos, dar palestras, etc. Só não acho que ter acesso ao Github e outros dará mais voz a opinião alheia.

Concluindo, entendo e concordo em parte com suas ideias, Vinicius, só não acho que qualquer pessoa ter acesso a essas ferramentas sem antes demonstrar o que quer fazer e principalmente, ser envolvido e estar de acordo com as ideias da comunidade Python. Você, por exemplo, se quiser te passo tudo pois sei que está envolvido e engajado. Agora, passar pra outra pessoa que aparece uma vez e quer ter acesso, aí não rola.

Repito, qualquer pessoa pode fazer o que bem entender e estamos aqui para ajudar no que for preciso, mas não necessariamente tenho que dar acesso a tudo. Não ter acesso é um fator limitante para que a pessoa não realize o que deseja?

Sugiro novamente que essa discussão seja levada ao Google Groups. Fico à disposição no que precisarem.

Abraço!

**Comment by drgarcia1986** [comment]
Assino embaixo :point_up:

**Comment by vmesel** [comment]
Vamos responder por pontos:

Primeiramente: nunca me senti ofendido/lesado/prejudicado por nenhum membro da organização do GruPy, até por eu ser um dos membros e nunca me senti denegrido de forma alguma.

A parte de poucas pessoas terem acesso as ferramentas que mantém o grupo ativo, faz sentido já que são poucas que tocam o barco como Eu e o Régis e outras várias pessoas que já fizeram organizações de diversos eventos Python em São Paulo.

Acho que eu fui um chucro na hora de escrever o argumento do:

```
Discordo de termos poucas pessoas responsáveis na administração da organização já que eu acho essencial que todos possam participar de decisões, se não, não seria uma comunidade, seria uma empresa
```

Realmente temos pessoas envolvidas, mas temos muitas pessoas da antiga que não se manifestam mais no movimento Python SP que estão como liderança do grupo como o chester e etc... Poderiamos ou fazer estas pessoas voltarem a ser ativas na comunidade, ou deixa-las como membros normais pois já não acumulam função dentro de nosso círculo há certo tempo.

Sobre os meios de comunicação da comunidade, estamos cometendo alguns pecados em termos tantos meios de comunicação e usarmos eles tão pouco, acredito que devemos fazer uma manutenção em toda a comunidade para podermos cresce-la e colocar mais pessoas novas a se engajarem com nossos projetos. Poderiamos focar somente no Telegram, Twitter e Google Groups, assim todos saberiam o que estaria rolando e não teria que ficar procurando uma certa interação em uma rede social diferente da que ele se encontra.

Se todos concordarem, eu gostaria do acesso a org do GitHub e gostaria que déssemos para o Régis também, já que ele é um dos contribuintes desta comunidade.

Concluindo, agradeço tudo o que a comunidade fez até agora, mas precisamos começar a pensar no futuro da nossa comunidade para começarmos 2017 com grande estímulo e força de vontade para podermos ter os melhores encontros de todos os anos.

Quanto a sugestão da migração desta discussão, a efetuarei mais tarde!

**Comment by drgarcia1986** [comment]
@vmesel resumidamente pra ajudar a galera que for ver a issue e não tem muito tempo pra ler textão, você consegue dar um motivo pratico (não filosófico) do pq deveríamos dar acesso a você ou a qualquer outro como membro da organização do grupy-sp aqui no github? (Além do acesso que você já tem nesse repositório?)

**Comment by vmesel** [comment]
Por eu estar com um projeto de reestruturação dos eventos incluindo uma parte de tutoriais, um site novo, ferramentas feitas por nós. Além do mais, nós que somos os líderes da comunidade atualmente temos que propagar mais trabalho python.

A minha adição a organização serviria para poder iniciar o desenvolvimento de tutoriais que serviriam para a comunidade ao todo d gostaria que fosse uma iniciativa do GruPy, não pessoal minha. Um projeto que tenho em mente seria a adição de um repositório explicando o básico até o avançado de Python.

**Comment by drgarcia1986** [comment]
Pra mim a discussão encerra aqui:

> Além do mais, nós que somos os líderes da comunidade atualmente

Não acredito que comunidades de software tenham lideres e nem que se isso exista, esses devem ou não ter privilégios. Eu só estava como membro da organização por ter mais tempo (trabalho com o github diariamente) para ajudar, porém me retiro agora.

**Comment by dunossauro** [comment]
Caralho, quanto mimimi. Manda um PR, quando alguém tiver um tempo, o mesmo aceita. Pronto.

**Comment by vmesel** [comment]
Encerrado o assunto, fica a critério do @erichideki e do @drgarcia1986 a resolução do assunto! Ponto final

**Comment by rg3915** [comment]
Não perca o próximo #FS2W #5 Introdução ao Git do @grupysp
http://meetu.ps/37nqPm

<http://www.onlinehtmleditor.net/>

Regis Santos
Web Developer

[image: Aboutme] <http://rg3915.github.io/> [image: matrix]
<http://grandeportal.github.io/> [image: Aboutme]
<https://about.me/rg3915> [image:
Linkedin] <https://www.linkedin.com/in/regis-da-silva-santos> [image:
github] <https://github.com/rg3915>
