### ISSUE TITLE
VAGA: DESENVOLVEDOR PYTHON

### ISSUE THREAD

**Issue by CapitaniIT** [grupy-sp/encontros#67]
Conhecimentos necessários:
Desenvolvimento em linguagem Python
Conhecimento sobre Docker
Conhecimento sobre Git
Desenvolvimento de testes unitários
Desenvolvimento de BDDs
Conhecimento sobre deploys automáticos

Conhecimentos desejáveis:
Participação na implementação de algum chatbot
Conhecimento sobre Blip
Conhecimento sobre Websocket
Conhecimento sobre AWS
Conhecimento sobre Jenkins

Local: Centro (Anhangabaú) / SP
Envie seu currículo para fabio.coelho@capitani.com.br

**Comment by dunossauro** [comment]
@CapitaniIT, já pensou em anunciar essa vaga no [pybojs](https://pyjobs.com.br/)?
